server:
  port: 8089
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /demo

spring:
  profiles:
    active: local

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

  messages:
    basename: static/i18n/messages

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.intertek.demo.system.entity,com.intertek.demo.job.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

